services:
  redis:
    image: redis:7.2-alpine
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"

  app:
    image: overkill-fibonacci
    hostname: fibonacci-api
    env_file:
      - infrastructure/.docker.env
    extra_hosts:
      - "docker.host:${DOCKER_HOST_IP}"
    ports:
      - "8000:8000"
    user: "www-data:www-data"
    volumes:
      - ".:/var/www/apps/fibonacci:cached"
    command: symfony server:start

  cli:
    image: overkill-fibonacci
    env_file:
      - infrastructure/.docker.env
    extra_hosts:
      - "docker.host:${DOCKER_HOST_IP}"
    links:
      - app
      - redis
    user: "${UID}"
    volumes:
      - ".:/var/www/apps/fibonacci:cached"
    command: bash
